name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev or prod)'
        required: true
        default: 'dev' 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ">= 1.2.0, < 2.0.0"
        # env:
        #     AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        #     AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Terraform commands 
        run: |
         terraform init
         terraform validate
         terraform workspace select  ${{ github.event.inputs.environment }} || terraform workspace new  ${{ github.event.inputs.environment }}
         terraform plan --var-file="variables\${{ github.event.inputs.environment }}.tfvars" 
         terraform apply -auto-approve --var-file="variables\${{ github.event.inputs.environment }}.tfvars"
