name: Terraform CI/CD

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ">= 1.2.0, < 2.0.0"
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Terraform providers
        run: terraform init

      # - name: Select terraform workspace dev 
      #   run: terraform workspace new dev && terraform workspace select dev

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply
